name = "gomandap-server"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[vars]
R2_BUCKET_NAME = "gomandap"
R2_ENDPOINT = "https://ac8f9f6e8039432372115201f4b75de5.r2.cloudflarestorage.com"

[[d1_databases]]
binding = "DB"
database_name = "gomandap-db"
database_id = "e3bc7e3e-2af7-4031-88f2-7e9f9df9ba4f"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gomandap"
